 runtime-predictions:
  predict_bacteria_before_analysis:
    model: ml_bacteria_prediction
    trigger:
      type: Periodic
      every: 60s
      from:
        selectSampleTask: started
      to:
        analyzeSampleTask: started
     
    decision:
      aggregated:
        operator: AND
        conditions:
          - field: Probability
            operator: GTE
            value: 0.85
          - field: PredictedClass
            operator: EQ
            value: "yes"  
      onTrue:
        native:
          - action: Set Variable
            name: bacteriaDetected
            value: "yes"
        direct:
          - operation: Cancel
            element-id: selectSampleTask
            priority: 10
          - operation: Activate
            element-id: moveToGarbageTask
            priority: 1


